### ISSUE TITLE
Male UMA Emotion not working

### ISSUE THREAD

**Issue by tricky30de** [TheWizardsCode/Character#36]
I tried the emotions and interests animation with the male uma and the WIP Emotions Scene.
I set up animations in the talk blendtree. Also I add the Animation Layer Controller for the connection with Salsa. Slasa Lipsynch is also on the UMA Avatar and working with Mic Input. When I start the Scene only the Visimes from Salsa are played not the anims from the Talking Layer. I saw in your youtube explination video, ther is a confiqure uma for salsa script. Is this needed for working propper?

**Comment by SorraTheOrc** [comment]
Hmmm.... let me try to reproduce...

**Comment by SorraTheOrc** [comment]
Have you added talk animations to your project? [EDIT: After re-reading your report I see you have added animations... taking another look]. As noted in the text of the WIP scene intro "This scene currently doesn't demonstrate these emotions well as the character doesn't have animations to demonstrate their impact." If you haven't added animations then all you will see is the emotion values changing.

I'm in the middle of creating a bunch of placeholder poses so that you will actually see movement even if you haven't provided your own animations.

**Comment by SorraTheOrc** [comment]
OK, I've repro'd the problem in a clean project. It's another issue with my merging the Animations Repo with the Character Repo. I'm working on it and taking the opportunity to do some refactoring too.

**Comment by SorraTheOrc** [comment]
I have integrated the new poses with the WIP scene. I've not yet tested with Salsa, but it is working standalone. I'll continue working on this soon, but assuming I've not also broken the salsa integrations this should now work with the poses (meaning it will be jerky, but indicative). If you add your own animations it should work. Note, however, I have not yet done poses for all the talk animations, it's still a WIP.

The changes are not yet merged with main, you can find them in the v0.1.1 branch https://github.com/TheWizardsCode/Character/tree/v0.1.1

**Comment by tricky30de** [comment]
I will try it in a new project. First I must deinstall your package. It get's erros while build.
cannot build player while editor is importing assets or compiling scripts

**Comment by SorraTheOrc** [comment]
I believe this issue, including build errors, have been resolved. Please feel free to reopen this issue if that's not the case.
